// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取成绩请求
type GradeRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Xqm                  string   `protobuf:"bytes,2,opt,name=xqm,proto3" json:"xqm,omitempty"`
	Xnm                  string   `protobuf:"bytes,3,opt,name=xnm,proto3" json:"xnm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GradeRequest) Reset()         { *m = GradeRequest{} }
func (m *GradeRequest) String() string { return proto.CompactTextString(m) }
func (*GradeRequest) ProtoMessage()    {}
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *GradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeRequest.Unmarshal(m, b)
}
func (m *GradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeRequest.Marshal(b, m, deterministic)
}
func (m *GradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeRequest.Merge(m, src)
}
func (m *GradeRequest) XXX_Size() int {
	return xxx_messageInfo_GradeRequest.Size(m)
}
func (m *GradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GradeRequest proto.InternalMessageInfo

func (m *GradeRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *GradeRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GradeRequest) GetXqm() string {
	if m != nil {
		return m.Xqm
	}
	return ""
}

func (m *GradeRequest) GetXnm() string {
	if m != nil {
		return m.Xnm
	}
	return ""
}

// 成绩返回值
type GradeReply struct {
	Lists                []*GradeItem `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GradeReply) Reset()         { *m = GradeReply{} }
func (m *GradeReply) String() string { return proto.CompactTextString(m) }
func (*GradeReply) ProtoMessage()    {}
func (*GradeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *GradeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeReply.Unmarshal(m, b)
}
func (m *GradeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeReply.Marshal(b, m, deterministic)
}
func (m *GradeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeReply.Merge(m, src)
}
func (m *GradeReply) XXX_Size() int {
	return xxx_messageInfo_GradeReply.Size(m)
}
func (m *GradeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GradeReply proto.InternalMessageInfo

func (m *GradeReply) GetLists() []*GradeItem {
	if m != nil {
		return m.Lists
	}
	return nil
}

// 成绩列表 item
type GradeItem struct {
	Kcmc                 string   `protobuf:"bytes,1,opt,name=Kcmc,proto3" json:"Kcmc,omitempty"`
	Kcxzmc               string   `protobuf:"bytes,2,opt,name=Kcxzmc,proto3" json:"Kcxzmc,omitempty"`
	Cj                   string   `protobuf:"bytes,3,opt,name=Cj,proto3" json:"Cj,omitempty"`
	Jsxm                 string   `protobuf:"bytes,4,opt,name=Jsxm,proto3" json:"Jsxm,omitempty"`
	Kclbmc               string   `protobuf:"bytes,5,opt,name=Kclbmc,proto3" json:"Kclbmc,omitempty"`
	Xf                   string   `protobuf:"bytes,6,opt,name=Xf,proto3" json:"Xf,omitempty"`
	Kcgsmc               string   `protobuf:"bytes,7,opt,name=Kcgsmc,proto3" json:"Kcgsmc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GradeItem) Reset()         { *m = GradeItem{} }
func (m *GradeItem) String() string { return proto.CompactTextString(m) }
func (*GradeItem) ProtoMessage()    {}
func (*GradeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *GradeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeItem.Unmarshal(m, b)
}
func (m *GradeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeItem.Marshal(b, m, deterministic)
}
func (m *GradeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeItem.Merge(m, src)
}
func (m *GradeItem) XXX_Size() int {
	return xxx_messageInfo_GradeItem.Size(m)
}
func (m *GradeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeItem.DiscardUnknown(m)
}

var xxx_messageInfo_GradeItem proto.InternalMessageInfo

func (m *GradeItem) GetKcmc() string {
	if m != nil {
		return m.Kcmc
	}
	return ""
}

func (m *GradeItem) GetKcxzmc() string {
	if m != nil {
		return m.Kcxzmc
	}
	return ""
}

func (m *GradeItem) GetCj() string {
	if m != nil {
		return m.Cj
	}
	return ""
}

func (m *GradeItem) GetJsxm() string {
	if m != nil {
		return m.Jsxm
	}
	return ""
}

func (m *GradeItem) GetKclbmc() string {
	if m != nil {
		return m.Kclbmc
	}
	return ""
}

func (m *GradeItem) GetXf() string {
	if m != nil {
		return m.Xf
	}
	return ""
}

func (m *GradeItem) GetKcgsmc() string {
	if m != nil {
		return m.Kcgsmc
	}
	return ""
}

// 获取课表请求
type TableRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Xqm                  string   `protobuf:"bytes,2,opt,name=xqm,proto3" json:"xqm,omitempty"`
	Xnm                  string   `protobuf:"bytes,3,opt,name=xnm,proto3" json:"xnm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableRequest) Reset()         { *m = TableRequest{} }
func (m *TableRequest) String() string { return proto.CompactTextString(m) }
func (*TableRequest) ProtoMessage()    {}
func (*TableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *TableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRequest.Unmarshal(m, b)
}
func (m *TableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRequest.Marshal(b, m, deterministic)
}
func (m *TableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRequest.Merge(m, src)
}
func (m *TableRequest) XXX_Size() int {
	return xxx_messageInfo_TableRequest.Size(m)
}
func (m *TableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TableRequest proto.InternalMessageInfo

func (m *TableRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *TableRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TableRequest) GetXqm() string {
	if m != nil {
		return m.Xqm
	}
	return ""
}

func (m *TableRequest) GetXnm() string {
	if m != nil {
		return m.Xnm
	}
	return ""
}

// 课表返回值
type TableReply struct {
	Lists                []*TableItem `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TableReply) Reset()         { *m = TableReply{} }
func (m *TableReply) String() string { return proto.CompactTextString(m) }
func (*TableReply) ProtoMessage()    {}
func (*TableReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *TableReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableReply.Unmarshal(m, b)
}
func (m *TableReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableReply.Marshal(b, m, deterministic)
}
func (m *TableReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableReply.Merge(m, src)
}
func (m *TableReply) XXX_Size() int {
	return xxx_messageInfo_TableReply.Size(m)
}
func (m *TableReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TableReply.DiscardUnknown(m)
}

var xxx_messageInfo_TableReply proto.InternalMessageInfo

func (m *TableReply) GetLists() []*TableItem {
	if m != nil {
		return m.Lists
	}
	return nil
}

// 课表列表 item
type TableItem struct {
	Kcmc                 string   `protobuf:"bytes,1,opt,name=Kcmc,proto3" json:"Kcmc,omitempty"`
	Zcd                  string   `protobuf:"bytes,2,opt,name=Zcd,proto3" json:"Zcd,omitempty"`
	Jcor                 string   `protobuf:"bytes,3,opt,name=Jcor,proto3" json:"Jcor,omitempty"`
	Cdmc                 string   `protobuf:"bytes,4,opt,name=Cdmc,proto3" json:"Cdmc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableItem) Reset()         { *m = TableItem{} }
func (m *TableItem) String() string { return proto.CompactTextString(m) }
func (*TableItem) ProtoMessage()    {}
func (*TableItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *TableItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableItem.Unmarshal(m, b)
}
func (m *TableItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableItem.Marshal(b, m, deterministic)
}
func (m *TableItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableItem.Merge(m, src)
}
func (m *TableItem) XXX_Size() int {
	return xxx_messageInfo_TableItem.Size(m)
}
func (m *TableItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TableItem.DiscardUnknown(m)
}

var xxx_messageInfo_TableItem proto.InternalMessageInfo

func (m *TableItem) GetKcmc() string {
	if m != nil {
		return m.Kcmc
	}
	return ""
}

func (m *TableItem) GetZcd() string {
	if m != nil {
		return m.Zcd
	}
	return ""
}

func (m *TableItem) GetJcor() string {
	if m != nil {
		return m.Jcor
	}
	return ""
}

func (m *TableItem) GetCdmc() string {
	if m != nil {
		return m.Cdmc
	}
	return ""
}

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GradeRequest)(nil), "data.GradeRequest")
	proto.RegisterType((*GradeReply)(nil), "data.GradeReply")
	proto.RegisterType((*GradeItem)(nil), "data.GradeItem")
	proto.RegisterType((*TableRequest)(nil), "data.TableRequest")
	proto.RegisterType((*TableReply)(nil), "data.TableReply")
	proto.RegisterType((*TableItem)(nil), "data.TableItem")
	proto.RegisterType((*HelloRequest)(nil), "data.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "data.HelloReply")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0xaf, 0x12, 0x31,
	0x14, 0x7d, 0xf3, 0xf1, 0x78, 0x72, 0x25, 0x3a, 0x69, 0xa2, 0x69, 0xde, 0xea, 0xa5, 0x89, 0xe6,
	0xad, 0xde, 0x02, 0x5c, 0xb9, 0x71, 0x81, 0x09, 0x22, 0x1b, 0x83, 0x9a, 0x20, 0x2b, 0x4b, 0x5b,
	0x26, 0x90, 0xe9, 0xcc, 0xd0, 0x16, 0x1d, 0xfc, 0x2b, 0xfe, 0x17, 0x7f, 0x9b, 0x69, 0xa7, 0xe5,
	0x23, 0x41, 0x59, 0xbd, 0xdd, 0xbd, 0x87, 0x73, 0xee, 0xb9, 0x3d, 0xdc, 0x01, 0xe0, 0xd4, 0xd0,
	0x87, 0x5a, 0x55, 0xa6, 0x42, 0xa9, 0xad, 0xc9, 0x77, 0xe8, 0x8d, 0x14, 0xe5, 0x62, 0x2a, 0x36,
	0x5b, 0xa1, 0x0d, 0xca, 0x20, 0xd1, 0x2b, 0x8e, 0xa3, 0xbb, 0xe8, 0xbe, 0x3b, 0xb5, 0x25, 0xba,
	0x85, 0x27, 0x35, 0xd5, 0xfa, 0x67, 0xa5, 0x38, 0x4e, 0x1d, 0xbc, 0xef, 0x2d, 0xbb, 0xd9, 0x48,
	0x1c, 0xb7, 0xec, 0x66, 0x23, 0x1d, 0x52, 0x4a, 0x9c, 0x78, 0xa4, 0x94, 0x64, 0x00, 0xe0, 0x1d,
	0xea, 0x62, 0x87, 0x5e, 0xc1, 0x75, 0xb1, 0xd2, 0x46, 0xe3, 0xe8, 0x2e, 0xb9, 0x7f, 0xda, 0x7f,
	0xfe, 0xe0, 0x36, 0x72, 0x84, 0xb1, 0x11, 0x72, 0xda, 0xfe, 0x4a, 0x7e, 0x47, 0xd0, 0xdd, 0x83,
	0x08, 0x41, 0x3a, 0x61, 0x92, 0xf9, 0xad, 0x5c, 0x8d, 0x5e, 0x42, 0x67, 0xc2, 0x9a, 0x5f, 0x92,
	0x79, 0x77, 0xdf, 0xa1, 0x67, 0x10, 0x0f, 0xd7, 0xde, 0x3f, 0x1e, 0xae, 0xad, 0xf6, 0xa3, 0x6e,
	0xa4, 0x5f, 0xdd, 0xd5, 0xad, 0xb6, 0x58, 0x48, 0x86, 0xaf, 0x83, 0xd6, 0x76, 0x56, 0x3b, 0x5b,
	0xe2, 0x4e, 0xab, 0x9d, 0x2d, 0x5b, 0x5e, 0xae, 0x25, 0xc3, 0x37, 0x81, 0x67, 0x3b, 0x1b, 0xda,
	0x17, 0xba, 0x28, 0x1e, 0x37, 0x34, 0xef, 0xf0, 0xef, 0xd0, 0x1c, 0xe1, 0x38, 0xb4, 0x6f, 0xd0,
	0xdd, 0x63, 0x67, 0x33, 0xcb, 0x20, 0x99, 0x33, 0x1e, 0x9c, 0xe7, 0x8c, 0xbb, 0x74, 0x58, 0xa5,
	0xbc, 0xb5, 0xab, 0x2d, 0x36, 0xe4, 0x92, 0x85, 0xc4, 0x6c, 0x4d, 0x08, 0xf4, 0x3e, 0x88, 0xa2,
	0xa8, 0xc2, 0x8b, 0x11, 0xa4, 0x25, 0x95, 0x22, 0x4c, 0xb7, 0x35, 0x79, 0x0d, 0xe0, 0x39, 0x76,
	0x67, 0x0c, 0x37, 0x52, 0x68, 0x4d, 0xf3, 0x40, 0x0a, 0x6d, 0xff, 0x4f, 0x0c, 0xbd, 0xf7, 0xd4,
	0xd0, 0x4f, 0xaa, 0xfa, 0xb1, 0xe2, 0x42, 0xa1, 0x37, 0x00, 0xb9, 0x30, 0x9f, 0xcd, 0x76, 0x5c,
	0x2e, 0x2b, 0x84, 0xda, 0xd7, 0x1d, 0xdb, 0xdd, 0x66, 0x27, 0x58, 0x5d, 0xec, 0xc8, 0x15, 0x7a,
	0x07, 0x2f, 0x72, 0x61, 0xbe, 0x96, 0x5c, 0xa8, 0x5c, 0x51, 0xbe, 0xa5, 0x46, 0xb8, 0x8b, 0x09,
	0x03, 0x8e, 0xcf, 0x3a, 0x0c, 0x38, 0x1c, 0xe2, 0xf9, 0x01, 0x2e, 0xbe, 0xff, 0x0d, 0x38, 0xfc,
	0x29, 0xe4, 0x0a, 0xbd, 0x85, 0x2c, 0x17, 0x66, 0x74, 0xce, 0xfc, 0xe2, 0xf6, 0xa7, 0xda, 0x13,
	0xdf, 0x4b, 0xda, 0x45, 0xc7, 0x7d, 0xc0, 0x83, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x82, 0xbe,
	0xdd, 0x34, 0xce, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataProviderClient is the client API for DataProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataProviderClient interface {
	// 获取基本个人信息
	GetStuInfo(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// 获取本科生成绩
	GetUndergraduateGrade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeReply, error)
	// 获取本科生课表
	GetUndergraduateTable(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*TableReply, error)
	// 获取研究生成绩
	GetGraduateGrade(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// 获取研究生课表
	GetGraduateTable(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type dataProviderClient struct {
	cc *grpc.ClientConn
}

func NewDataProviderClient(cc *grpc.ClientConn) DataProviderClient {
	return &dataProviderClient{cc}
}

func (c *dataProviderClient) GetStuInfo(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/data.DataProvider/getStuInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProviderClient) GetUndergraduateGrade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeReply, error) {
	out := new(GradeReply)
	err := c.cc.Invoke(ctx, "/data.DataProvider/getUndergraduateGrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProviderClient) GetUndergraduateTable(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*TableReply, error) {
	out := new(TableReply)
	err := c.cc.Invoke(ctx, "/data.DataProvider/getUndergraduateTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProviderClient) GetGraduateGrade(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/data.DataProvider/getGraduateGrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProviderClient) GetGraduateTable(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/data.DataProvider/getGraduateTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProviderServer is the server API for DataProvider service.
type DataProviderServer interface {
	// 获取基本个人信息
	GetStuInfo(context.Context, *HelloRequest) (*HelloReply, error)
	// 获取本科生成绩
	GetUndergraduateGrade(context.Context, *GradeRequest) (*GradeReply, error)
	// 获取本科生课表
	GetUndergraduateTable(context.Context, *GradeRequest) (*TableReply, error)
	// 获取研究生成绩
	GetGraduateGrade(context.Context, *HelloRequest) (*HelloReply, error)
	// 获取研究生课表
	GetGraduateTable(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedDataProviderServer can be embedded to have forward compatible implementations.
type UnimplementedDataProviderServer struct {
}

func (*UnimplementedDataProviderServer) GetStuInfo(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStuInfo not implemented")
}
func (*UnimplementedDataProviderServer) GetUndergraduateGrade(ctx context.Context, req *GradeRequest) (*GradeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUndergraduateGrade not implemented")
}
func (*UnimplementedDataProviderServer) GetUndergraduateTable(ctx context.Context, req *GradeRequest) (*TableReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUndergraduateTable not implemented")
}
func (*UnimplementedDataProviderServer) GetGraduateGrade(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGraduateGrade not implemented")
}
func (*UnimplementedDataProviderServer) GetGraduateTable(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGraduateTable not implemented")
}

func RegisterDataProviderServer(s *grpc.Server, srv DataProviderServer) {
	s.RegisterService(&_DataProvider_serviceDesc, srv)
}

func _DataProvider_GetStuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServer).GetStuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProvider/GetStuInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServer).GetStuInfo(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProvider_GetUndergraduateGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServer).GetUndergraduateGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProvider/GetUndergraduateGrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServer).GetUndergraduateGrade(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProvider_GetUndergraduateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServer).GetUndergraduateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProvider/GetUndergraduateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServer).GetUndergraduateTable(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProvider_GetGraduateGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServer).GetGraduateGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProvider/GetGraduateGrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServer).GetGraduateGrade(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProvider_GetGraduateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServer).GetGraduateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.DataProvider/GetGraduateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServer).GetGraduateTable(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataProvider",
	HandlerType: (*DataProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStuInfo",
			Handler:    _DataProvider_GetStuInfo_Handler,
		},
		{
			MethodName: "getUndergraduateGrade",
			Handler:    _DataProvider_GetUndergraduateGrade_Handler,
		},
		{
			MethodName: "getUndergraduateTable",
			Handler:    _DataProvider_GetUndergraduateTable_Handler,
		},
		{
			MethodName: "getGraduateGrade",
			Handler:    _DataProvider_GetGraduateGrade_Handler,
		},
		{
			MethodName: "getGraduateTable",
			Handler:    _DataProvider_GetGraduateTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
